pull_request_rules:
  - name: automatic merge when CI passes and review approved
    conditions:
      - base=master
      - '#approved-reviews-by>=1'
      - '#review-requested=0'
      - '#changes-requested-reviews-by=0'
      - '#commented-reviews-by=0'
      - 'status-success=WIP'
    actions:
      merge:
        method: merge
        strict: smart
        strict_method: rebase
      delete_head_branch:

  - name: add label to hotfix branches
    conditions:
      - base=master
      - head~=^hotfix/
    actions:
      label:
        add:
          - hotfix

  - name: backport patches to release branches
    conditions:
      - base=master
      - label=hotfix
    actions:
      backport:
        regexes:
          - ^release/

  - name: automatic merge for backport
    conditions:
      - base~=^release/
      - head~=^mergify/bp/
      - '#approved-reviews-by>=1'
    actions:
      merge:
        method: merge
        strict: true
        strict_method: rebase
      delete_head_branch:

  - name: delete head branch when closed
    conditions:
      - closed
    actions:
      delete_head_branch:
