import AdultBadge from 'src/assets/svg/AdultBadge.svg';
import StarRating from 'src/assets/svg/StarRating.svg';
import NoStarRating from 'src/assets/svg/NoStarRating.svg';
import RidiWaitFree from 'src/assets/svg/RidiWaitFree.svg';
import VerticalArrow from 'src/assets/svg/VerticalArrow.svg';
import Clock from 'src/assets/svg/Clock.svg';
import Author from 'src/assets/svg/Author.svg';
import RidiBooksLogo from 'src/assets/svg/RidiLogo.svg';
import RidiSelectLogo from 'src/assets/svg/RidiSelectLogo.svg';
import CaretDown from 'src/assets/svg/CaretDown.svg';
import Check from 'src/assets/svg/Check.svg';

export const ADULT_BADGE_URL = AdultBadge;
export const STAR_RATING_URL = StarRating;
export const NO_STAR_RATING_URL = NoStarRating;
export const RIDI_WAIT_FREE_ICON_URL = RidiWaitFree;
export const VERTICAL_RIGHT_ARROW_ICON_URL = VerticalArrow;
export const CLOCK_ICON_URL = Clock;
export const AUTHOR_ICON_URL = Author;
export const RIDIBOOKS_LOGO_URL = RidiBooksLogo;
export const RIDISELECT_LOGO_URL = RidiSelectLogo;
export const CARET_DOWN_ICON_URL = CaretDown;
export const CHECK_ICON_URL = Check;
