export default () => (
  <>
    <meta
      name="msapplication-TileImage"
      content={`${publicRuntimeConfig.STATIC_CDN_URL}/static/favicon/favicon_win8.png`}
    />
    <meta name="msapplication-TileColor" content="#1f8ee6" />
    <link
      rel="shortcut icon"
      href={`${publicRuntimeConfig.STATIC_CDN_URL}/static/favicon/favicon.ico`}
    />

    <link
      rel="apple-touch-icon"
      sizes="57x57"
      href={`${publicRuntimeConfig.STATIC_CDN_URL}/static/favicon/apple-icon-57x57.png?150320`}
    />
    <link
      rel="apple-touch-icon"
      sizes="60x60"
      href={`${publicRuntimeConfig.STATIC_CDN_URL}/static/favicon/apple-icon-60x60.png?150320`}
    />
    <link
      rel="apple-touch-icon"
      sizes="72x72"
      href={`${publicRuntimeConfig.STATIC_CDN_URL}/static/favicon/apple-icon-72x72.png?150320`}
    />
    <link
      rel="apple-touch-icon"
      sizes="76x76"
      href={`${publicRuntimeConfig.STATIC_CDN_URL}/static/favicon/apple-icon-76x76.png?150320`}
    />
    <link
      rel="apple-touch-icon"
      sizes="114x114"
      href={`${publicRuntimeConfig.STATIC_CDN_URL}/static/favicon/apple-icon-114x114.png?150320`}
    />
    <link
      rel="apple-touch-icon"
      sizes="120x120"
      href={`${publicRuntimeConfig.STATIC_CDN_URL}/static/favicon/apple-icon-120x120.png?150320`}
    />
    <link
      rel="apple-touch-icon"
      sizes="144x144"
      href={`${publicRuntimeConfig.STATIC_CDN_URL}/static/favicon/apple-icon-144x144.png?150320`}
    />
    <link
      rel="apple-touch-icon"
      sizes="152x152"
      href={`${publicRuntimeConfig.STATIC_CDN_URL}/static/favicon/apple-icon-152x152.png?150320`}
    />
    <link
      rel="apple-touch-icon"
      sizes="180x180"
      href={`${publicRuntimeConfig.STATIC_CDN_URL}/static/favicon/apple-icon-180x180.png?150320`}
    />
    <link
      rel="icon"
      type="image/png"
      sizes="192x192"
      href={`${publicRuntimeConfig.STATIC_CDN_URL}/static/favicon/android-icon-192x192.png?150320`}
    />

    <link
      rel="apple-touch-icon"
      sizes="180x180"
      href={`${publicRuntimeConfig.STATIC_CDN_URL}/static/favicon/apple-touch-icon.png?190528`}
    />
    <link
      rel="icon"
      type="image/png"
      sizes="32x32"
      href={`${publicRuntimeConfig.STATIC_CDN_URL}/static/favicon/favicon-32x32.png?190528`}
    />
    <link
      rel="icon"
      type="image/png"
      sizes="16x16"
      href={`${publicRuntimeConfig.STATIC_CDN_URL}/static/favicon/favicon-16x16.png?190528`}
    />
    <link
      rel="icon"
      type="image/png"
      sizes="192x192"
      href={`${publicRuntimeConfig.STATIC_CDN_URL}/static/favicon/android-chrome-192x192.png?190528`}
    />
  </>
);
