export default [
  { id: '509000028', title: '데미안', author: '헤르만 헤세', serviceAtSelect: false },
  {
    id: '1648000213',
    title: '나는 습관을 조금 바꾸기로 했다',
    author: '사사키 후미',
    serviceAtSelect: true,
  },
  { id: '745000127', title: '깃털 도둑', author: '커크 월리스 존스', serviceAtSelect: false },
  { id: '102073049', title: '소근소근', author: 'Kzu', serviceAtSelect: false },
  {
    id: '1546000541',
    title: '팩트풀니스',
    author: '한스 로슬링 외 2명',
    serviceAtSelect: true,
  },
  {
    id: '2016000096',
    title: '재밌다고들 하지만 나는 두 번 다시 하지 않을 일',
    author: '데이비드 포스터 월리스와 데이비드 포스터',
    serviceAtSelect: true,
  },
  {
    id: '1046000023',
    title: '그랜드 부다페스트 호텔',
    author: '매트 졸러 세이츠',
    serviceAtSelect: false,
  },
  { id: '809019926', title: '슬립워커', author: '워커 슬림', serviceAtSelect: false },
  { id: '371001619', title: '요즘 우울하십니까?', author: '김언희', serviceAtSelect: false },
  {
    id: '2093025396',
    title: '은하수를 횡단하는 택시 운전사',
    author: '히치하이커',
    serviceAtSelect: false,
  },
  {
    id: '1242000653',
    title: '백치',
    author: '표도르 미하일로비치 도스토예프스키',
    serviceAtSelect: false,
  },
  {
    id: '1669000008',
    title: '존재의 세 가지 거짓말',
    author: '아고타 크리스토프',
    serviceAtSelect: false,
  },
  {
    id: '2066000857',
    title: '나「」만「」의「」비「」밀「(나만의 비밀)',
    author: '스미노 요루, 김현화',
    serviceAtSelect: false,
  },
  {
    id: '962000026',
    title: '소셜커머스 광고마케팅 보고서',
    author: 'DMC미디어 R&D팀',
    serviceAtSelect: false,
  },
  {
    id: '2093025396',
    title: '은하수를 횡단하는 택시 운전사',
    author: '한유담',
    serviceAtSelect: false,
  },
  {
    id: '1242000653',
    title: '백치',
    author: '표도르 미하일로비치 도스토예프스키',
    serviceAtSelect: false,
  },
  {
    id: '1669000008',
    title: '존재의 세 가지 거짓말',
    author: '아고타 크리스토프',
    serviceAtSelect: false,
  },
  {
    id: '2066000857',
    title: '나「」만「」의「」비「」밀「(나만의 비밀)',
    author: '스미노 요루, 김현화',
    serviceAtSelect: false,
  },
];
